# Generated by Django 4.2.3 on 2024-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('game_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
