# Generated by Django 4.2.3 on 2024-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_snakescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinosaurScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlappyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
